# fly.toml app configuration file generated for neil-listmonk on 2023-12-12T09:30:04-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "neil-listmonk"
console_command = "/bin/sh"
primary_region = "iad"
swap_size_mb = 512

[build]
image = "listmonk/listmonk:v4.0.0-rc-3"

[deploy]
release_command = "./listmonk --upgrade --yes"

[env]
LISTMONK_app__address = "0.0.0.0:8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
